#!/bin/sh
##/etc/init.d/lbs-server Lv : S90

## This file is boot script of /usr/bin/lbs-server

if [ -x /usr/bin/lbs-server ]; then
	if [ ! -z "`pgrep lbs-server`" ]; then
		/usr/bin/killall lbs-server
	fi
	/usr/bin/lbs-server &
fi
